# Generated by Django 4.2.9 on 2026-01-11 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_remove_account_dian_concept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Resolución 1876... - Doc Soporte', max_length=100)),
                ('doc_type', models.CharField(choices=[('INVOICE', 'Factura Electrónica de Venta'), ('SUPPORT_DOC', 'Documento Soporte en Adquisiciones')], default='SUPPORT_DOC', max_length=20, verbose_name='Tipo Documento')),
                ('prefix', models.CharField(max_length=10, verbose_name='Prefijo')),
                ('number', models.CharField(max_length=100, verbose_name='Número Resolución')),
                ('start_range', models.BigIntegerField(verbose_name='Desde')),
                ('end_range', models.BigIntegerField(verbose_name='Hasta')),
                ('current_number', models.BigIntegerField(help_text='Siguiente número a usar', verbose_name='Consecutivo Actual')),
                ('start_date', models.DateField(verbose_name='Fecha Resolución')),
                ('end_date', models.DateField(verbose_name='Fecha Vencimiento')),
                ('technical_key', models.CharField(blank=True, help_text='Solo para Factura Venta, Doc Soporte no suele usarla igual', max_length=255, verbose_name='Clave Técnica')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('consecutive', models.BigIntegerField()),
                ('issue_date', models.DateField(verbose_name='Fecha Emisión')),
                ('payment_due_date', models.DateField(verbose_name='Fecha Vencimiento')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha Recepción')),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dian_status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SIGNED', 'Firmado'), ('SENT', 'Enviado'), ('ACCEPTED', 'Aceptado por DIAN'), ('REJECTED', 'Rechazado')], default='DRAFT', max_length=20)),
                ('cuds', models.CharField(blank=True, max_length=255, verbose_name='CUDS (Código Único)')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='support_docs/xml/')),
                ('dian_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta DIAN')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_documents', to='invoicing.resolution')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_purchases', to='accounting.thirdparty', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Documento Soporte',
                'verbose_name_plural': 'Documentos Soporte',
                'unique_together': {('prefix', 'consecutive')},
            },
        ),
        migrations.CreateModel(
            name='SupportDocumentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Código Item')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio Unitario')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje IVA (0, 5, 19)', max_digits=5)),
                ('total_line', models.DecimalField(decimal_places=2, max_digits=14)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.supportdocument')),
            ],
        ),
    ]
