# Generated by Django 4.2.9 on 2026-01-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio Venta')),
                ('type', models.CharField(choices=[('PRODUCTO', 'Producto (Bien)'), ('SERVICIO', 'Servicio')], default='SERVICIO', max_length=20, verbose_name='Tipo')),
                ('tax_type', models.CharField(choices=[('IVA_19', 'IVA General 19%'), ('IVA_5', 'IVA Reducido 5%'), ('EXENTO', 'Exento (0%)'), ('EXCLUIDO', 'Excluido (Sin IVA)')], default='IVA_19', max_length=20, verbose_name='Tipo Impuesto')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto/Servicio',
                'verbose_name_plural': 'Productos y Servicios',
                'ordering': ['code'],
            },
        ),
    ]
