# Generated by Django 4.2.9 on 2026-01-12 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_accountingtemplate_accountingtemplateline'),
        ('invoicing', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('number', models.BigIntegerField(verbose_name='Número')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='Fecha Emisión')),
                ('payment_due_date', models.DateField(verbose_name='Fecha Vencimiento')),
                ('payment_term', models.CharField(choices=[('CONTADO', 'De Contado'), ('30_DIAS', 'Crédito 30 Días'), ('60_DIAS', 'Crédito 60 Días')], default='CONTADO', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Guardada'), ('VOID', 'Anulada')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.thirdparty', verbose_name='Cliente')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.resolution')),
            ],
            options={
                'verbose_name': 'Factura de Venta',
                'verbose_name_plural': 'Facturas de Venta',
                'unique_together': {('prefix', 'number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.item')),
            ],
        ),
    ]
