# Generated by Django 4.2.9 on 2026-01-12 20:36

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('invoicing', '0003_invoice_invoiceline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicBillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('PRUEBAS', 'Habilitación / Pruebas'), ('PRODUCCION', 'Producción')], default='PRUEBAS', max_length=20, verbose_name='Ambiente DIAN')),
                ('software_id', models.CharField(help_text='Identificador único del software proporcionado por la DIAN', max_length=255, verbose_name='ID de Software')),
                ('software_pin', fernet_fields.fields.EncryptedCharField(help_text='PIN secreto entregado por la DIAN. Se guarda encriptado.', max_length=100, verbose_name='PIN del Software')),
                ('certificate_file', models.FileField(help_text='Archivo de firma digital emitido por una entidad certificadora (GSE, Andes, etc).', upload_to='private/certs/', verbose_name='Certificado Digital (.p12)')),
                ('certificate_password', fernet_fields.fields.EncryptedCharField(help_text='Contraseña para desencriptar la llave privada del certificado.', max_length=255, verbose_name='Contraseña Certificado')),
                ('invoice_test_set_id', models.CharField(blank=True, help_text='Identificador del set de pruebas para Factura Electrónica', max_length=255, null=True, verbose_name='Test Set ID (Facturación)')),
                ('payroll_test_set_id', models.CharField(blank=True, help_text='Identificador del set de pruebas para Nómina Electrónica', max_length=255, null=True, verbose_name='Test Set ID (Nómina)')),
                ('support_doc_test_set_id', models.CharField(blank=True, help_text='Identificador del set de pruebas para Documento Soporte', max_length=255, null=True, verbose_name='Test Set ID (Doc. Soporte)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_billing_config', to='tenants.client', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración Fiscal (DIAN)',
                'verbose_name_plural': 'Configuraciones Fiscales',
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PAYROLL', 'Nómina Electrónica'), ('PAYROLL_ADJUSTMENT', 'Nota de Ajuste de Nómina'), ('CREDIT_NOTE', 'Nota Crédito'), ('DEBIT_NOTE', 'Nota Débito')], max_length=30, verbose_name='Tipo de Documento')),
                ('prefix', models.CharField(blank=True, help_text='Opcional. Ej: NC, NE.', max_length=10, verbose_name='Prefijo Interno')),
                ('current_number', models.BigIntegerField(default=0, verbose_name='Consecutivo Actual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='tenants.client', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Secuencia de Documentos',
                'verbose_name_plural': 'Secuencias de Documentos',
                'unique_together': {('company', 'document_type', 'prefix')},
            },
        ),
        migrations.CreateModel(
            name='DianResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Factura Electrónica de Venta'), ('POS', 'Factura Electrónica POS'), ('SUPPORT_DOCUMENT', 'Documento Soporte en Adquisiciones')], default='INVOICE', max_length=30, verbose_name='Tipo de Documento')),
                ('prefix', models.CharField(blank=True, help_text='Ej: SETT. Dejar en blanco si no tiene prefijo.', max_length=10, verbose_name='Prefijo')),
                ('resolution_number', models.CharField(help_text='Número oficial del formulario 1876', max_length=100, verbose_name='Número de Resolución')),
                ('date_from', models.DateField(verbose_name='Fecha Inicio Vigencia')),
                ('date_to', models.DateField(verbose_name='Fecha Fin Vigencia')),
                ('number_from', models.BigIntegerField(verbose_name='Rango Desde')),
                ('number_to', models.BigIntegerField(verbose_name='Rango Hasta')),
                ('current_number', models.BigIntegerField(help_text='El próximo documento tomará este número + 1 (o este número si no se ha usado).', verbose_name='Consecutivo Actual')),
                ('technical_key', fernet_fields.fields.EncryptedCharField(blank=True, help_text='Clave técnica de la resolución. Se guarda encriptada.', max_length=255, null=True, verbose_name='Clave Técnica')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicing_dian_resolutions', to='tenants.client', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Resolución DIAN',
                'verbose_name_plural': 'Resoluciones DIAN',
                'ordering': ['-date_from'],
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.dianresolution'),
        ),
        migrations.AlterField(
            model_name='supportdocument',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_documents', to='invoicing.dianresolution', verbose_name='Resolución'),
        ),
        migrations.DeleteModel(
            name='Resolution',
        ),
    ]
