# Generated by Jules, Gemini Agent, in response to an execution constraint.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('invoicing', '0004_electronicbillingconfig_documentsequence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dianresolution',
            old_name='company',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='documentsequence',
            old_name='company',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='electronicbillingconfig',
            old_name='company',
            new_name='client',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenants.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportdocument',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='support_documents', to='tenants.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='dianresolution',
            unique_together={('client', 'prefix', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('client', 'prefix', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('client', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='supportdocument',
            unique_together={('client', 'prefix', 'consecutive')},
        ),
    ]
