# Stage 1: Build React App
FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
# Clean install para CI/CD
RUN npm ci 
COPY . .
# Aumentar memoria para el build si es necesario
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine
# Copiar el build de React
COPY --from=build /app/dist /usr/share/nginx/html
# Copiar configuración custom de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
