# Generated by Django 5.0.1 on 2026-01-10 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('nature', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=10, verbose_name='Naturaleza')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clase de Cuenta',
                'verbose_name_plural': 'Clases de Cuentas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounting.accountclass')),
            ],
            options={
                'verbose_name': 'Grupo de Cuenta',
                'verbose_name_plural': 'Grupos de Cuentas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('level', models.IntegerField(verbose_name='Nivel')),
                ('nature', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=10, verbose_name='Naturaleza')),
                ('account_type', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('COSTO', 'Costo de Ventas')], max_length=20, verbose_name='Tipo de Cuenta')),
                ('allows_movement', models.BooleanField(default=True, verbose_name='Permite Movimientos')),
                ('requires_third_party', models.BooleanField(default=False, verbose_name='Requiere Tercero')),
                ('requires_cost_center', models.BooleanField(default=False, verbose_name='Requiere Centro de Costo')),
                ('manages_retention', models.BooleanField(default=False, verbose_name='Maneja Retención')),
                ('is_tax_account', models.BooleanField(default=False, verbose_name='Cuenta de Impuestos')),
                ('tax_type', models.CharField(blank=True, choices=[('IVA', 'IVA'), ('RETEFUENTE', 'Retención en la Fuente'), ('RETEIVA', 'Retención de IVA'), ('RETEICA', 'Retención de ICA'), ('CREE', 'CREE')], max_length=50, verbose_name='Tipo de Impuesto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account', verbose_name='Cuenta Padre')),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.accountgroup')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.costcenter', verbose_name='Centro de Costo Padre')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('entry_type', models.CharField(choices=[('APERTURA', 'Apertura'), ('DIARIO', 'Diario'), ('AJUSTE', 'Ajuste'), ('CIERRE', 'Cierre'), ('NOTA', 'Nota Contable')], max_length=20, verbose_name='Tipo de Comprobante')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia Externa')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Contabilizado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Contabilización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Adjuntos')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_posted', to=settings.AUTH_USER_MODEL, verbose_name='Contabilizado por')),
            ],
            options={
                'verbose_name': 'Comprobante Contable',
                'verbose_name_plural': 'Comprobantes Contables',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor'), ('EMPLEADO', 'Empleado'), ('SOCIO', 'Socio'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Tercero')),
                ('person_type', models.IntegerField(choices=[(1, 'Persona Jurídica'), (2, 'Persona Natural')], verbose_name='Tipo de Persona')),
                ('identification_type', models.CharField(choices=[('11', 'Registro civil'), ('12', 'Tarjeta de identidad'), ('13', 'Cédula de ciudadanía'), ('21', 'Tarjeta de extranjería'), ('22', 'Cédula de extranjería'), ('31', 'NIT'), ('41', 'Pasaporte'), ('42', 'Documento de identificación extranjero'), ('47', 'PEP - Permiso Especial de Permanencia'), ('50', 'NIT de otro país'), ('91', 'NUIP')], max_length=2, verbose_name='Tipo de Identificación DIAN')),
                ('identification_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('check_digit', models.CharField(blank=True, help_text='Obligatorio para NIT (31) - Calculado con Módulo 11', max_length=1, verbose_name='Dígito de Verificación (DV)')),
                ('business_name', models.CharField(blank=True, help_text='Obligatorio si es Persona Jurídica', max_length=255, verbose_name='Razón Social')),
                ('trade_name', models.CharField(blank=True, help_text='Opcional - Nombre con el que se conoce comercialmente', max_length=200, verbose_name='Nombre Comercial')),
                ('first_name', models.CharField(blank=True, help_text='Obligatorio si es Persona Natural', max_length=60, verbose_name='Primer Nombre')),
                ('middle_name', models.CharField(blank=True, max_length=60, verbose_name='Segundo Nombre')),
                ('surname', models.CharField(blank=True, help_text='Obligatorio si es Persona Natural', max_length=60, verbose_name='Primer Apellido')),
                ('second_surname', models.CharField(blank=True, max_length=60, verbose_name='Segundo Apellido')),
                ('country_code', models.CharField(default='CO', help_text='CO para Colombia', max_length=2, verbose_name='Código País (ISO 3166-1)')),
                ('department_code', models.CharField(help_text='Ej: 76=Valle, 11=Bogotá, 05=Antioquia', max_length=2, verbose_name='Código DANE Departamento')),
                ('city_code', models.CharField(help_text='Ej: 76001=Cali, 11001=Bogotá, 05001=Medellín', max_length=5, verbose_name='Código DANE Municipio')),
                ('postal_code', models.CharField(help_text='Obligatorio para Facturación Electrónica - 6 dígitos en Colombia', max_length=10, verbose_name='Código Postal')),
                ('address', models.TextField(verbose_name='Dirección Completa')),
                ('tax_regime', models.CharField(choices=[('48', 'Responsable de IVA (Antes Régimen Común)'), ('49', 'No Responsable de IVA (Antes Régimen Simplificado)'), ('42', 'Régimen Simple de Tributación')], default='49', max_length=2, verbose_name='Régimen Tributario DIAN')),
                ('fiscal_responsibilities', models.JSONField(default=list, help_text='Códigos DIAN: O-13=Gran Contribuyente, O-15=Autorretenedor, O-23=Agente Retención IVA, O-47=Régimen Simple, R-99-PN=No aplica', verbose_name='Responsabilidades Fiscales')),
                ('ciiu_code', models.CharField(blank=True, help_text='Vital para calcular tarifa de ICA según municipio', max_length=10, verbose_name='Código CIIU (Actividad Económica)')),
                ('email', models.EmailField(help_text='Correo donde llegará el XML y PDF de la factura electrónica', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono Principal')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Celular')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('bank_account_type', models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=20, verbose_name='Tipo de Cuenta')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Cuenta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_parties', to='accounting.account', verbose_name='Cuenta Contable Por Defecto')),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
                'ordering': ['business_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(verbose_name='Línea')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Débito')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Crédito')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Base')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='accounting.account', verbose_name='Cuenta')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='accounting.costcenter', verbose_name='Centro de Costo')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='Comprobante')),
                ('third_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='accounting.thirdparty', verbose_name='Tercero')),
            ],
            options={
                'verbose_name': 'Movimiento Contable',
                'verbose_name_plural': 'Movimientos Contables',
                'ordering': ['entry', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='accounting__code_c93a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type'], name='accounting__account_889d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_28dd04_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='accounting__date_e3f521_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status'], name='accounting__status_0a2ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_type'], name='accounting__entry_t_5e6cde_idx'),
        ),
        migrations.AddIndex(
            model_name='thirdparty',
            index=models.Index(fields=['identification_number'], name='accounting__identif_505949_idx'),
        ),
        migrations.AddIndex(
            model_name='thirdparty',
            index=models.Index(fields=['party_type'], name='accounting__party_t_5113f9_idx'),
        ),
        migrations.AddIndex(
            model_name='thirdparty',
            index=models.Index(fields=['person_type'], name='accounting__person__1d714f_idx'),
        ),
        migrations.AddIndex(
            model_name='thirdparty',
            index=models.Index(fields=['tax_regime'], name='accounting__tax_reg_f0a778_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['entry', 'line_number'], name='accounting__entry_i_cd64dc_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account'], name='accounting__account_6fdc67_idx'),
        ),
    ]
