# Generated by Django 4.2.9 on 2026-01-11 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DianFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código Formato')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Formato')),
                ('version', models.IntegerField(default=1, verbose_name='Versión')),
                ('valid_from', models.IntegerField(verbose_name='Año Vigencia')),
            ],
            options={
                'verbose_name': 'Formato DIAN',
                'verbose_name_plural': 'Formatos DIAN (Exógena)',
                'ordering': ['code', 'version'],
                'unique_together': {('code', 'version', 'valid_from')},
            },
        ),
        migrations.CreateModel(
            name='DianConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código Concepto')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre del Concepto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='accounting.dianformat', verbose_name='Formato')),
            ],
            options={
                'verbose_name': 'Concepto DIAN',
                'verbose_name_plural': 'Conceptos DIAN',
                'ordering': ['code'],
                'unique_together': {('format', 'code')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='dian_concept',
            field=models.ForeignKey(blank=True, help_text='Concepto específico dentro del formato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounting.dianconcept', verbose_name='Concepto DIAN'),
        ),
        migrations.AddField(
            model_name='account',
            name='dian_format',
            field=models.ForeignKey(blank=True, help_text='Formato para reporte de información exógena', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounting.dianformat', verbose_name='Formato DIAN'),
        ),
    ]
