# Generated by Django 4.2.9 on 2026-01-11 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_dianformat_dianconcept_account_dian_concept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='dian_concept',
        ),
        migrations.RemoveField(
            model_name='account',
            name='dian_format',
        ),
        migrations.CreateModel(
            name='AccountDianConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dian_configurations', to='accounting.account')),
                ('dian_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.dianconcept', verbose_name='Concepto')),
                ('dian_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.dianformat', verbose_name='Formato')),
            ],
            options={
                'verbose_name': 'Configuración DIAN de Cuenta',
                'verbose_name_plural': 'Configuraciones DIAN de Cuentas',
                'unique_together': {('account', 'dian_format', 'dian_concept')},
            },
        ),
    ]
