# Generated by Django 4.2.9 on 2026-01-12 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounting', '0003_remove_account_dian_concept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código/Prefijo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('current_number', models.PositiveIntegerField(default=0, verbose_name='Consecutivo Actual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Contable',
                'verbose_name_plural': 'Tipos de Documentos Contables',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.accountingdocumenttype', verbose_name='Tipo de Documento'),
        ),
    ]
