# Generated by Django 4.2.9 on 2026-01-12 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accountingdocumenttype_journalentry_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de Plantilla')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='accounting.accountingdocumenttype', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Plantilla Contable',
                'verbose_name_plural': 'Plantillas Contables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountingTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=10, verbose_name='Naturaleza')),
                ('calculation_method', models.CharField(choices=[('FIXED_VALUE', 'Valor Fijo'), ('PERCENTAGE_OF_SUBTOTAL', '% del Subtotal'), ('PERCENTAGE_OF_TOTAL', '% del Total'), ('PERCENTAGE_OF_TAX', '% del Impuesto'), ('PLUG', 'Diferencia (Plug) / Saldo')], max_length=30, verbose_name='Método de Cálculo')),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Si es porcentaje, usar 19.00 para 19%. Si es PLUG, dejar en 0.', max_digits=10, verbose_name='Valor / Porcentaje')),
                ('description_template', models.CharField(help_text='Variables disponibles: {numero}, {tercero}, {fecha}', max_length=255, verbose_name='Plantilla de Descripción')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='Cuenta Contable')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.accountingtemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Línea de Plantilla Contable',
                'verbose_name_plural': 'Líneas de Plantillas Contables',
                'ordering': ['id'],
            },
        ),
    ]
