# Generated by Django 4.2.9 on 2026-01-11 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_remove_account_dian_concept_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DianResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_number', models.CharField(max_length=100, verbose_name='Número Resolución (Form. 1876)')),
                ('prefix', models.CharField(help_text='Ej: DSE', max_length=10, verbose_name='Prefijo')),
                ('from_number', models.BigIntegerField(verbose_name='Desde')),
                ('to_number', models.BigIntegerField(verbose_name='Hasta')),
                ('current_number', models.BigIntegerField(default=0, verbose_name='Consecutivo Actual')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio Vigencia')),
                ('end_date', models.DateField(verbose_name='Fecha Fin Vigencia')),
                ('technical_key', models.CharField(help_text='Hexadecimal largo proporcionado en la resolución', max_length=255, verbose_name='Llave Técnica DIAN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dian_resolutions', to='tenants.client')),
            ],
        ),
        migrations.CreateModel(
            name='SupportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.BigIntegerField(verbose_name='Consecutivo')),
                ('issue_date', models.DateField(verbose_name='Fecha Emisión')),
                ('payment_due_date', models.DateField(verbose_name='Fecha Vencimiento')),
                ('payment_method', models.CharField(choices=[('1', 'Contado'), ('2', 'Crédito')], default='1', max_length=10)),
                ('dian_status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviado'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado')], default='DRAFT', max_length=20, verbose_name='Estado DIAN')),
                ('cuds', models.CharField(blank=True, max_length=255, null=True, verbose_name='CUDS')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='support_docs/xml/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='support_docs/pdf/')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_documents', to='tenants.client')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='support_docs.dianresolution')),
            ],
            options={
                'verbose_name': 'Documento Soporte',
                'verbose_name_plural': 'Documentos Soporte',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.thirdparty',),
        ),
        migrations.CreateModel(
            name='SupportDocumentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Subtotal Línea')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Impuestos/Retenciones')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='support_docs.supportdocument')),
            ],
        ),
        migrations.AddField(
            model_name='supportdocument',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_documents_as_supplier', to='support_docs.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='supportdocument',
            unique_together={('resolution', 'consecutive')},
        ),
    ]
