# Generated by Django 5.0.1 on 2026-01-10 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, verbose_name='ID del Cliente')),
                ('sync_type', models.CharField(max_length=50, verbose_name='Tipo de Sincronización')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('records_sent', models.IntegerField(default=0, verbose_name='Registros Enviados')),
                ('records_received', models.IntegerField(default=0, verbose_name='Registros Recibidos')),
                ('records_failed', models.IntegerField(default=0, verbose_name='Registros Fallidos')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sync_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Sincronización',
                'verbose_name_plural': 'Logs de Sincronización',
                'ordering': ['-created_at'],
            },
        ),
    ]
