# Generated by Django 4.2.9 on 2026-01-11 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_remove_account_dian_concept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código Empleado')),
                ('contract_type', models.CharField(choices=[('FIJO', 'Término Fijo'), ('INDEFINIDO', 'Término Indefinido'), ('OBRA', 'Obra o Labor'), ('APRENDIZAJE', 'Aprendizaje')], max_length=20, verbose_name='Tipo de Contrato')),
                ('start_date', models.DateField(verbose_name='Fecha Ingreso')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salario Base')),
                ('transport_allowance_eligible', models.BooleanField(default=True, verbose_name='Aplica Aux. Transporte')),
                ('health_entity', models.CharField(max_length=100, verbose_name='EPS')),
                ('pension_entity', models.CharField(max_length=100, verbose_name='Fondo Pensiones')),
                ('severance_entity', models.CharField(max_length=100, verbose_name='Fondo Cesantías')),
                ('arl_entity', models.CharField(max_length=100, verbose_name='ARL')),
                ('risk_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nivel Riesgo ARL')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='Centro de Costo')),
                ('third_party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='accounting.thirdparty', verbose_name='Tercero')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Periodo')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('payment_date', models.DateField(verbose_name='Fecha Pago')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('LIQUIDATED', 'Liquidado'), ('PAID', 'Pagado'), ('REPORTED', 'Transmitido DIAN')], default='DRAFT', max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Año Fiscal')),
                ('min_wage', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salario Mínimo Legal (SMMLV)')),
                ('transport_allowance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Auxilio de Transporte')),
                ('uvt_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor UVT')),
                ('weekly_hours_semester_1', models.DecimalField(decimal_places=1, default=44, max_digits=4, verbose_name='Horas Semanales (Sem 1)')),
                ('weekly_hours_semester_2', models.DecimalField(decimal_places=1, default=42, max_digits=4, verbose_name='Horas Semanales (Sem 2)')),
                ('sunday_surcharge_semester_1', models.DecimalField(decimal_places=2, default=1.8, max_digits=4, verbose_name='Factor Dom/Fest (Sem 1)')),
                ('sunday_surcharge_semester_2', models.DecimalField(decimal_places=2, default=1.9, max_digits=4, verbose_name='Factor Dom/Fest (Sem 2)')),
            ],
            options={
                'verbose_name': 'Parámetros de Nómina',
                'verbose_name_plural': 'Parámetros de Nómina',
            },
        ),
        migrations.CreateModel(
            name='PayrollDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cune', models.CharField(blank=True, max_length=255, unique=True, verbose_name='CUNE')),
                ('conseccutive', models.IntegerField(verbose_name='Consecutivo')),
                ('prefix', models.CharField(blank=True, max_length=10, verbose_name='Prefijo')),
                ('worked_days', models.IntegerField(default=30, verbose_name='Días Trabajados')),
                ('accrued_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Devengado')),
                ('deductions_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Deducciones')),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neto a Pagar')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='payroll_xmls/')),
                ('dian_status', models.CharField(default='PENDING', max_length=20, verbose_name='Estado DIAN')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_documents', to='payroll.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='payroll.payrollperiod')),
            ],
            options={
                'unique_together': {('period', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_type', models.CharField(choices=[('EARNING', 'Devengado'), ('DEDUCTION', 'Deducción')], max_length=20)),
                ('dian_code', models.CharField(max_length=50, verbose_name='Código DIAN')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Cantidad (Horas/Días)')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.payrolldocument')),
            ],
            options={
                'verbose_name': 'Detalle de Nómina',
            },
        ),
    ]
