# Generated by Django 4.2.9 on 2026-01-11 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNovelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('days', models.PositiveIntegerField(help_text='Días a reportar en nómina', verbose_name='Días')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='novelties/', verbose_name='Soporte')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novelties', to='payroll.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Novedad Empleado',
                'verbose_name_plural': 'Novedades Empleados',
            },
        ),
        migrations.CreateModel(
            name='LegalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('SMMLV', 'Salario Mínimo Legal Vigente'), ('AUX_TRANS', 'Auxilio de Transporte'), ('MAX_WEEKLY_HOURS', 'Jornada Máxima Semanal'), ('UVT', 'Unidad de Valor Tributario')], db_index=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor monetario o numérico', max_digits=12)),
                ('valid_from', models.DateField(help_text='Fecha de inicio de la vigencia')),
                ('valid_to', models.DateField(blank=True, help_text='Fecha fin (Dejar vacío si es vigente indefinidamente)', null=True)),
            ],
            options={
                'verbose_name': 'Parámetro Legal',
                'verbose_name_plural': 'Parámetros Legales',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='NoveltyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Código Interno')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Novedad')),
                ('dian_type', models.CharField(choices=[('LNR', 'Licencia No Remunerada'), ('IGE', 'Incapacidad General'), ('LMA', 'Licencia Maternidad/Paternidad'), ('VAC', 'Vacaciones'), ('IRL', 'Incapacidad Laboral (ARL)'), ('OTR', 'Otra Novedad')], max_length=3, verbose_name='Tipo DIAN')),
                ('payroll_payment_percentage', models.DecimalField(decimal_places=4, default=0.0, help_text='Porcentaje del salario que recibe el empleado (Ej: 0.6667 para el 66.67%)', max_digits=5, verbose_name='% Pago Nómina')),
                ('affects_transport_aid', models.BooleanField(default=True, help_text='Si es True, NO se paga auxilio de transporte esos días', verbose_name='Afecta Aux. Trans')),
                ('pays_health', models.BooleanField(default=True, help_text='¿Se cotiza salud?', verbose_name='Cotiza Salud')),
                ('pays_pension', models.BooleanField(default=True, help_text='¿Se cotiza pensión?', verbose_name='Cotiza Pensión')),
                ('pays_arl', models.BooleanField(default=False, help_text='¿Se cotiza ARL?', verbose_name='Cotiza ARL')),
            ],
            options={
                'verbose_name': 'Tipo de Novedad',
                'verbose_name_plural': 'Tipos de Novedades',
            },
        ),
        migrations.DeleteModel(
            name='PayrollSettings',
        ),
        migrations.AddField(
            model_name='employeenovelty',
            name='novelty_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.noveltytype', verbose_name='Tipo Novedad'),
        ),
    ]
