# Generated by Django 4.2.9 on 2026-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employeenovelty_legalparameter_noveltytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalparameter',
            name='key',
            field=models.CharField(choices=[('SMMLV', 'Salario Mínimo Legal Vigente'), ('AUX_TRANS', 'Auxilio de Transporte'), ('MAX_WEEKLY_HOURS', 'Jornada Máxima Semanal'), ('UVT', 'Unidad de Valor Tributario'), ('SURCHARGE_DOMINICAL', 'Recargo Dominical/Festivo')], db_index=True, max_length=50),
        ),
    ]
