# Generated by Django 4.2.9 on 2026-01-11 15:55

import apps.payroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_legalparameter_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeenovelty',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.payroll.models.novelty_file_path, verbose_name='Soporte'),
        ),
    ]
