# Generated by Django 4.2.9 on 2026-01-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_employeenovelty_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldocument',
            name='novelty_days',
            field=models.IntegerField(default=0, verbose_name='Días Novedad'),
        ),
    ]
