# Generated by Django 4.2.9 on 2026-01-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrolldocument_novelty_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldocument',
            name='dian_response',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta DIAN'),
        ),
    ]
