# Generated by Django 4.2.9 on 2026-01-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrolldocument_dian_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolldocument',
            name='cune',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='CUNE'),
        ),
    ]
