# Generated by Django 4.2.9 on 2026-01-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_payrolldocument_cune'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código Interno')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Concepto')),
                ('concept_type', models.CharField(choices=[('EARNING', 'Devengado'), ('DEDUCTION', 'Deducción')], max_length=20, verbose_name='Tipo')),
                ('dian_code', models.CharField(max_length=50, verbose_name='Código DIAN')),
                ('is_salary', models.BooleanField(default=False, verbose_name='Es Salario (Base Prestacional)')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de cálculo si aplica (Ej: 25.00 para HED)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Concepto de Nómina',
                'verbose_name_plural': 'Conceptos de Nómina',
            },
        ),
    ]
