# Generated by Django 4.2.9 on 2026-01-12 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_nit', models.CharField(max_length=20, verbose_name='NIT Proveedor')),
                ('issuer_name', models.CharField(max_length=200, verbose_name='Razón Social Proveedor')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Número de Factura')),
                ('cufe', models.CharField(max_length=255, unique=True, verbose_name='CUFE')),
                ('issue_date', models.DateField(verbose_name='Fecha Emisión Factura')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total Factura')),
                ('xml_file', models.FileField(upload_to='inbox/xml/', verbose_name='XML Original')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='inbox/pdf/', verbose_name='PDF Representación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invoices', to='tenants.client', verbose_name='Adquirente (Nosotros)')),
            ],
            options={
                'verbose_name': 'Factura Recibida',
                'verbose_name_plural': 'Facturas Recibidas',
            },
        ),
        migrations.CreateModel(
            name='InvoiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(choices=[('030', '030 - Acuse de Recibo'), ('032', '032 - Recibo del Bien y/o Prestación del Servicio'), ('033', '033 - Aceptación Expresa'), ('034', '034 - Reclamo (Rechazo)')], max_length=3, verbose_name='Código Evento')),
                ('consecutive', models.IntegerField(help_text='Consecutivo único por tipo de evento y emisor', verbose_name='Consecutivo Evento')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Generación')),
                ('cude', models.CharField(blank=True, max_length=255, verbose_name='CUDE')),
                ('xml_sent', models.FileField(blank=True, null=True, upload_to='events/xml/', verbose_name='XML Evento Enviado')),
                ('dian_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('dian_message', models.TextField(blank=True, verbose_name='Respuesta DIAN')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='electronic_events.receivedinvoice')),
            ],
            options={
                'verbose_name': 'Evento Electrónico',
                'verbose_name_plural': 'Eventos Electrónicos',
                'unique_together': {('invoice', 'event_code')},
            },
        ),
    ]
