# Generated by Django 4.2.9 on 2026-01-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedinvoice',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Subtotal (Sin Impuestos)'),
        ),
        migrations.AddField(
            model_name='receivedinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total Impuestos'),
        ),
    ]
