# Generated by Django 5.0.1 on 2026-01-10 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DIANResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Resolución')),
                ('resolution_date', models.DateField(verbose_name='Fecha de Resolución')),
                ('prefix', models.CharField(blank=True, max_length=10, verbose_name='Prefijo')),
                ('start_number', models.IntegerField(verbose_name='Desde')),
                ('end_number', models.IntegerField(verbose_name='Hasta')),
                ('current_number', models.IntegerField(verbose_name='Número Actual')),
                ('valid_from', models.DateField(verbose_name='Válida Desde')),
                ('valid_to', models.DateField(verbose_name='Válida Hasta')),
                ('technical_key', models.CharField(blank=True, max_length=255, verbose_name='Clave Técnica')),
                ('test_set_id', models.CharField(blank=True, max_length=100, verbose_name='Test Set ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_test', models.BooleanField(default=False, verbose_name='Es de Prueba')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resolución DIAN',
                'verbose_name_plural': 'Resoluciones DIAN',
                'ordering': ['-resolution_date'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Factura de Venta'), ('CREDIT_NOTE', 'Nota Crédito'), ('DEBIT_NOTE', 'Nota Débito'), ('PAYROLL', 'Nómina Electrónica'), ('SUPPORT_DOCUMENT', 'Documento Soporte')], max_length=20, verbose_name='Tipo de Documento')),
                ('prefix', models.CharField(blank=True, max_length=10, verbose_name='Prefijo')),
                ('number', models.CharField(max_length=50, verbose_name='Número')),
                ('full_number', models.CharField(max_length=60, unique=True, verbose_name='Número Completo')),
                ('issue_date', models.DateField(verbose_name='Fecha de Emisión')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('cufe', models.CharField(blank=True, max_length=255, unique=True, verbose_name='CUFE/CUDE')),
                ('qr_code', models.TextField(blank=True, verbose_name='Código QR')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Tasa de Cambio')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Impuestos')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Descuentos')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque'), ('CREDIT', 'Crédito')], default='CASH', max_length=20, verbose_name='Método de Pago')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='Términos de Pago')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente de Envío'), ('SENT', 'Enviado a DIAN'), ('ACCEPTED', 'Aceptado por DIAN'), ('REJECTED', 'Rechazado por DIAN'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('dian_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta DIAN')),
                ('dian_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado a DIAN')),
                ('dian_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceptado por DIAN')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='dian/xml/', verbose_name='Archivo XML')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='dian/pdf/', verbose_name='Archivo PDF')),
                ('attached_document', models.FileField(blank=True, null=True, upload_to='dian/attachments/', verbose_name='Documento Adjunto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronic_documents_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_documents', to='accounting.thirdparty', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Documento Electrónico',
                'verbose_name_plural': 'Documentos Electrónicos',
                'ordering': ['-issue_date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='DIANLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SEND', 'Envío'), ('QUERY', 'Consulta'), ('CANCEL', 'Anulación'), ('VALIDATE', 'Validación')], max_length=20, verbose_name='Acción')),
                ('status', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('ERROR', 'Error'), ('PENDING', 'Pendiente')], max_length=20, verbose_name='Estado')),
                ('request_data', models.JSONField(verbose_name='Datos de Solicitud')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Datos de Respuesta')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dian_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dian_logs', to='dian.electronicdocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Log DIAN',
                'verbose_name_plural': 'Logs DIAN',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(verbose_name='Línea')),
                ('product_code', models.CharField(max_length=50, verbose_name='Código del Producto')),
                ('product_name', models.CharField(max_length=300, verbose_name='Nombre del Producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Cantidad')),
                ('unit_of_measure', models.CharField(default='UND', max_length=10, verbose_name='Unidad de Medida')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Unitario')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Descuento')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% IVA')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_lines', to='accounting.account', verbose_name='Cuenta Contable')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dian.electronicdocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Línea de Documento',
                'verbose_name_plural': 'Líneas de Documentos',
                'ordering': ['document', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('IVA', 'IVA'), ('INC', 'INC (Impuesto Nacional al Consumo)'), ('RETEFUENTE', 'Retención en la Fuente'), ('RETEIVA', 'Retención de IVA'), ('RETEICA', 'Retención de ICA')], max_length=20, verbose_name='Categoría')),
                ('default_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa por Defecto (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_types', to='accounting.account', verbose_name='Cuenta Contable')),
            ],
            options={
                'verbose_name': 'Tipo de Impuesto',
                'verbose_name_plural': 'Tipos de Impuestos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicDocumentTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Base Gravable')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='dian.electronicdocument', verbose_name='Documento')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='dian.electronicdocumentline', verbose_name='Línea')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dian.taxtype', verbose_name='Tipo de Impuesto')),
            ],
            options={
                'verbose_name': 'Impuesto de Documento',
                'verbose_name_plural': 'Impuestos de Documentos',
            },
        ),
        migrations.AddIndex(
            model_name='electronicdocument',
            index=models.Index(fields=['full_number'], name='dian_electr_full_nu_ea11d2_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicdocument',
            index=models.Index(fields=['issue_date'], name='dian_electr_issue_d_3839f8_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicdocument',
            index=models.Index(fields=['status'], name='dian_electr_status_f40854_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicdocument',
            index=models.Index(fields=['cufe'], name='dian_electr_cufe_698d44_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicdocument',
            index=models.Index(fields=['customer'], name='dian_electr_custome_fd2a7d_idx'),
        ),
    ]
