# Generated by Django 4.2.9 on 2026-01-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('legal_name', models.CharField(max_length=300, verbose_name='Razón Social')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('tax_regime', models.CharField(choices=[('COMUN', 'Régimen Común'), ('SIMPLIFICADO', 'Régimen Simplificado'), ('ESPECIAL', 'Régimen Especial')], default='COMUN', max_length=20, verbose_name='Régimen Tributario')),
                ('fiscal_responsibilities', models.JSONField(default=list, help_text='Códigos de responsabilidades fiscales según DIAN', verbose_name='Responsabilidades Fiscales')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(default='Cali', max_length=100, verbose_name='Ciudad')),
                ('department', models.CharField(default='Valle del Cauca', max_length=100, verbose_name='Departamento')),
                ('country', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('dian_software_id', models.CharField(blank=True, max_length=100, verbose_name='ID Software DIAN')),
                ('dian_test_set_id', models.CharField(blank=True, max_length=100, verbose_name='Test Set ID DIAN')),
                ('dian_certificate', models.FileField(blank=True, null=True, upload_to='dian_certificates/', verbose_name='Certificado Digital .p12')),
                ('certificate_password_encrypted', models.CharField(blank=True, max_length=500, verbose_name='Contraseña Certificado (Cifrada)')),
                ('dian_certificate_password', models.CharField(blank=True, max_length=255, verbose_name='Contraseña Certificado (Legacy - No usar)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo Empresa')),
                ('plan', models.CharField(choices=[('FREE', 'Gratuito'), ('BASIC', 'Básico'), ('PROFESSIONAL', 'Profesional'), ('ENTERPRISE', 'Empresarial')], default='FREE', max_length=20, verbose_name='Plan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sincronización Habilitada')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
            ],
            options={
                'verbose_name': 'Cliente/Empresa',
                'verbose_name_plural': 'Clientes/Empresas',
                'ordering': ['name'],
            },
        ),
    ]
